# Generated by Django 6.0.2 on 2026-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('salary', models.PositiveIntegerField(max_length=60000000)),
                ('hired_date', models.DateField(blank=True, unique=True)),
            ],
        ),
    ]
