# Generated by Django 6.0.2 on 2026-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.TextField(default=None, max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
