# Generated by Django 6.0.2 on 2026-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_employee_email_employee_role_alter_employee_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.CharField(default=None, max_length=60, unique=True),
        ),
    ]
